%define SYSCALL_PRINT_INT 0
%define SYSCALL_PRINT_UINT 1
%define SYSCALL_PRINT_HEX 2
%define SYSCALL_PRINT_FLOAT 3
%define SYSCALL_PRINT_DOUBLE 4
%define SYSCALL_PRINT_CHAR 5
%define SYSCALL_PRINT_STRING 6

%define SYSCALL_PRINT_REGISTERS 100
%define SYSCALL_PRINT_MEMORY 101

%define SYSCALL_INPUT_INT 10
%define SYSCALL_INPUT_UINT 11
%define SYSCALL_INPUT_HEX 12
%define SYSCALL_INPUT_FLOAT 13
%define SYSCALL_INPUT_DOUBLE 14
%define SYSCALL_INPUT_CHAR 15
%define SYSCALL_INPUT_STRING 16
