#define SC_EXIT (-1)
#define SC_PRINT_INT 0
#define SC_PRINT_UINT 1
#define SC_PRINT_HEX 2
#define SC_PRINT_FLT 3
#define SC_PRINT_DBL 4
#define SC_PRINT_CHAR 5
#define SC_PRINT_STR 6

#define SC_PRINT_REGISTERS 100
#define SC_PRINT_MEMORY 101
#define SC_PRINT_STACK 102
